# Generated by Django 5.2 on 2025-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
    ]
