# Generated by Django 5.2 on 2025-04-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_alter_position_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='tasker.position'),
        ),
    ]
