# Generated by Django 5.2 on 2025-04-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_remove_worker_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasker.position'),
            preserve_default=False,
        ),
    ]
