# Generated by Django 5.2 on 2025-04-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_alter_worker_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['name']},
        ),
    ]
