# Generated by Django 5.2 on 2025-04-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_alter_worker_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['is_completed', 'deadline']},
        ),
    ]
